Repository codeit-team8/rolling, pull requests merged in 2023-11, with the labels that each got.

#4 [#1] chore : GlobalStyle 적용
  src/App.jsx
Labels: 팔레트

#6 [#1] chore : font 사이즈, lint 수정
  .eslintrc.cjs
  src/styles/GlobalStyle.js
Labels: 팔레트

#7 [#1] chore : 절대 경로 설정
  index.html
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: 팔레트

#15 [#13] fix : 확장자 오류 fix
  src/components/Toast.jsx
  src/styles/font.css
Labels: bug

#16 [#14] feature : 리스트에 있는 카드 컴포넌트 추가
  src/assets/images/card_pattern_blue.png
  src/assets/images/card_pattern_green.png
  src/assets/images/card_pattern_purple.png
  src/assets/images/card_pattern_yellow.png
  src/components/ListCard/ListCard.jsx
  src/components/Toast/Toast.jsx
Labels: 컴포넌트

#18 [#11] feat : input 컴포넌트 추가
  src/components/common/TextInput.jsx
Labels: 컴포넌트

#19 [#8] feat : 메시지 카드 컴포넌트 스타일 구현
  config.webstorm.js
  src/assets/icons/deleted.svg
  src/components/MessageCard/Badge.jsx
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.style.jsx
Labels: 컴포넌트

#23 [#20] feat : Nav 바 컴포넌트 추가
  src/App.jsx
  src/assets/fonts/Poppins/Poppins-Bold.ttf
  src/assets/icons/logo.svg
  src/components/Nav/Nav.jsx
  src/main.jsx
  src/pages/Main.jsx
  src/pages/Post.jsx
  src/styles/font.css
Labels: 페이지

#25 [#22] 이모지 컴포넌트 만들기, PaperCard 스타일 모바일 미디어쿼리 적용
  src/components/Emoji/Emoji.jsx
  src/components/Emoji/EmojiPopover.jsx
  src/components/ListCard/ListCard.jsx
  src/components/Toast/Toast.jsx
Labels: 컴포넌트

#28 [#21] 공유 클릭
  index.html
  src/components/Share/PopOverPortal.jsx
  src/components/Share/Popover.jsx
  src/components/Share/shareKakao.jsx
  src/components/Toast/Toast.jsx
  src/pages/Post.jsx
Labels: 컴포넌트, 기능

#29 [#27] 프로필이미지 컴포넌트 생성
  src/assets/icons/avatar.svg
  src/components/common/ProfileImage.jsx
Labels: 컴포넌트

#33 [#30] AddButton 컴포넌트 생성
  src/assets/icons/plus.svg
  src/components/common/AddButton.jsx
Labels: 컴포넌트

#32 [#9] 드롭다운 컴포넌트
  src/assets/icons/arrow_bottom.svg
  src/assets/icons/arrow_top.svg
  src/components/Dropdown/Dropdown.jsx
Labels: 컴포넌트

#36 [#31] feature : 이모지 클릭
  package-lock.json
  package.json
  src/assets/icons/add-20.svg
  src/assets/icons/add-24.svg
  src/assets/icons/arrow_down.svg
  src/assets/mock/mockReactions.js
  src/components/Emoji/Emoji.jsx
  src/components/Emoji/EmojiAdd.jsx
  src/components/Emoji/EmojiList.jsx
  src/components/Emoji/EmojiPopover.jsx
  src/pages/Post.jsx
Labels: 컴포넌트, 모달

#38 [#24] feature : 리스트 페이지에서 드래그(모바일, 테블릿) / PC(캐럿버튼) 스크롤 기능 추가
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/arrow_left.svg
  src/assets/icons/arrow_right.svg
  src/components/Nav/Nav.jsx
  src/components/PaperCard/PaperCard.jsx
  src/pages/RollingPaperList.jsx
  src/styles/button/AddButton.jsx
  src/styles/button/ArrowButton.jsx
  src/styles/input/TextInput.jsx
  src/styles/profileImage/ProfileImage.jsx
  src/util/carousel.jsx
Labels: 컴포넌트, 기능

#41 [#40] 공유 버튼 컴포넌트 스타일 추가
  src/assets/icons/share.svg
  src/components/Share/Popover.jsx
  src/components/Share/PopoverPortal.jsx
  src/components/Share/Share.jsx
Labels: 컴포넌트

#42 [#34] 텍스트 에디터 컴포넌트
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/MessageCard/MessageCard.jsx
  src/components/TextEditor/TextEditor.jsx
  src/pages/FromPage.jsx
Labels: 컴포넌트

#46 [#44] 버튼 컴포넌트
  package-lock.json
  package.json
  src/styles/button/OutlineButtonStyle.jsx
  src/styles/button/PrimaryButtonStyle.jsx
  src/styles/fontType.js
Labels: 컴포넌트

#47 [#39] 롤링 페이퍼 헤더 컴포넌트 스타일
  .eslintignore
  src/App.jsx
  src/assets/mock/mockReactions.js
  src/components/Dropdown/Dropdown.jsx
  src/components/Emoji/EmojiAdd.jsx
  src/components/Emoji/EmojiList.jsx
  src/components/Header/PostHeader.jsx
  src/components/Header/PostHeader.style.jsx
  src/components/MessageCard/MessageCard.jsx
  src/components/Nav/Nav.jsx
  src/components/PaperCard/RollingPaperList.jsx
  src/components/Share/Share.jsx
  src/pages/Main.jsx
  src/pages/Post.jsx
  src/styles/HeaderLine.jsx
  src/styles/button/ButtonDivLine.jsx
  src/styles/profileImage/ProfileImage.jsx
  src/styles/profileImage/ProfileImageGroup.jsx
Labels: 컴포넌트

#43 [#37] 랜딩페이지
  src/assets/images/img_01.png
  src/assets/images/img_02.png
  src/components/Landing/Landing.jsx
  src/components/Landing/Landing.style.jsx
  src/pages/Main.jsx
  src/styles/button/OutlineButton.jsx
  src/styles/button/PrimaryButton.jsx
Labels: 페이지

#49 [#48] 이모지 모달창 모바일 스타일 수정
  src/components/Emoji/EmojiAdd.jsx
  src/pages/Main.jsx
Labels: bug

#51 [#50] 1차 리팩터링
  src/components/Emoji/EmojiAdd.jsx
  src/components/Header/PostHeader.style.jsx
  src/components/Nav/Nav.jsx
  src/components/Share/Popover.jsx
  src/components/Share/Share.jsx
  src/components/Share/ShareKakao.jsx
  src/styles/DivLine.jsx
  src/styles/HeaderLine.jsx
Labels: Refactoring

#52 [#35] 옵션 컴포넌트
  src/assets/icons/select.svg
  src/assets/mock/mockBackgroundImg.jsx
  src/components/Option/Option.jsx
  src/components/Option/Option.style.jsx
  src/styles/button/SelectIcon.jsx
Labels: 컴포넌트

#54 [#45] 프로필 선택 기능
  index.html
  src/App.jsx
  src/components/Profile/ProfileSelect.jsx
  src/pages/FromPage.jsx
  src/styles/profileImage/ProfileImage.jsx
Labels: 기능

#59 [#58] API 세팅
  .eslintrc.cjs
  src/api/Domain.js
  src/api/backgroundImages.js
  src/api/message.js
  src/api/profileImage.js
  src/api/recipients.js
  src/hooks/useAsync.js
Labels: 기능

#56 [#53] To 페이지
  src/App.jsx
  src/components/Option/Option.jsx
  src/components/Option/Option.style.jsx
  src/pages/To.jsx
  src/styles/button/OutlineButton.jsx
  src/styles/button/PrimaryButton.jsx
  src/styles/input/TextInput.jsx
Labels: bug, 페이지

#68 [#60] 롤링 페이퍼 리스트 페이지 구현
  src/App.jsx
  src/components/Option/Option.jsx
  src/components/PaperCard/PaperCard.jsx
  src/components/PaperCard/RollingPaperList.jsx
  src/pages/From.jsx
  src/pages/Main.jsx
  src/pages/PaperList.jsx
  src/styles/button/ArrowButton.jsx
  src/styles/profileImage/ProfileImageGroup.jsx
  src/util/backgroundColors.jsx
Labels: 페이지

#67 [#65] 에러 화면
  package-lock.json
  package.json
  src/App.jsx
  src/Error/ErrorFallback.jsx
  src/api/backgroundImages.js
  src/api/message.js
  src/api/profileImage.js
  src/api/recipients.js
  src/assets/images/Error.png
  src/components/Option/Option.jsx
  src/hooks/useAsync.js
Labels: 기능

#66 [#55] From 페이지 렌더링
  src/components/Dropdown/Dropdown.jsx
  src/components/Profile/ProfileSelect.jsx
  src/components/TextEditor/TextEditor.jsx
  src/pages/From.jsx
  src/styles/input/TextInput.jsx
Labels: 페이지

#61 [#57] 롤링페이퍼 페이지
  src/App.jsx
  src/api/message.js
  src/assets/mock/mockBackgroundImg.jsx
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.style.jsx
  src/components/MessageCard/MessageCardList.jsx
  src/components/MessageCard/PlusMessageCard.jsx
  src/pages/Post.jsx
  src/styles/button/AddButton.jsx
Labels: 페이지

#74 [#70] Post Header API 연결
  src/App.jsx
  src/components/Header/PostHeader.jsx
  src/components/PaperCard/PaperCard.jsx
  src/pages/Post.jsx
Labels: 기능

#77 [#75] From 생성하기 버튼 누를 때 에러 발생 해결
  src/pages/From.jsx
  src/styles/button/AddButton.jsx
Labels: bug

#84 [#81] 메세지 카드 클릭시 모달 창
  index.html
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.style.jsx
  src/components/Modal/MessageCardModal.jsx
  src/components/Modal/Modal.jsx
  src/hooks/useOnClickOutside.js
  src/pages/Post.jsx
Labels: 모달

#86 [#85] 공유 현재페이지 기준으로 변경
  src/components/Header/PostHeader.jsx
  src/components/Share/Popover.jsx
  src/components/Share/Share.jsx
  src/pages/Post.jsx
Labels: 기능

#88 [#81] 모바일 모달창 스타일 수정
  src/components/Modal/MessageCardModal.jsx
Labels: bug

#90 [#87] 프로필 이미지 400 에러 수정
  src/components/Header/PostHeader.jsx
  src/components/PaperCard/PaperCard.jsx
  src/components/Profile/ProfileSelect.jsx
  src/components/profileImage/ProfileImage.jsx
  src/components/profileImage/ProfileImageGroup.jsx
  src/components/profileImage/SelectedProfileImage.jsx
  src/pages/From.jsx
Labels: bug

#91 [#71] 무한 스크롤
  src/main.jsx
  src/pages/Post.jsx
Labels: 기능

#93 [#92] message card 숫자 카운터 수정
  src/components/Header/PostHeader.jsx
Labels: bug

#94 [#73]/edit 페이지로 이동하여 편집하기 보이는 페이지로 이동 , 휴지통 버튼을 누르면 삭제되고 카드 재정렬
  src/App.jsx
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.style.jsx
  src/pages/Edit.jsx
  src/pages/Post.jsx
Labels: 페이지, 기능

#96 [#95] 텍스트 에디터 폰트 사이즈 수정
  src/components/TextEditor/TextEditor.css
  src/components/TextEditor/TextEditor.jsx
Labels: bug

#99 [#89] 페이지 삭제 버튼 클릭시 페이지이동
  .eslintrc.cjs
  src/components/Modal/MessageCardModal.jsx
  src/pages/Post.jsx
Labels: 기능

#100 [#98] 모바일 텍스트 겹침 문제
  src/components/MessageCard/MessageCard.jsx
  src/components/MessageCard/MessageCard.style.jsx
Labels: bug

#83 [#72] 리액션 증감
  src/components/Emoji/EmojiAdd.jsx
  src/components/Emoji/EmojiList.jsx
  src/components/Emoji/EmojiPopover.jsx
  src/components/Header/PostHeader.jsx
  src/components/Header/PostHeader.style.jsx
  src/components/Share/Share.jsx
  src/pages/Post.jsx
Labels: 기능

#104 [#103] 모바일에서 리스트페이지에서 카드 이모지 쏠림 개선
  src/components/PaperCard/PaperCard.jsx
Labels: bug

#102 [#101] 모달을 띄웠으나 숫자 하얗게 생기는 문제 해결
  src/components/Modal/MessageCardModal.jsx
Labels: bug

#106 [#105] 휴지통 버튼 눌렀을 때 삭제와 동시에 모달 팝업이 나타나는 문제
  src/components/MessageCard/MessageCard.jsx
Labels: bug

#110 [#109] 이름이 너무 길 때 줄 바뀜 방지
  src/components/Header/PostHeader.style.jsx
  src/components/MessageCard/MessageCard.style.jsx
  src/components/PaperCard/PaperCard.jsx
Labels: bug

#113 [#73]/edit 페이지로 이동하여 편집 , 휴지통 버튼을 누르면 삭제되고 카드 재정렬
  src/App.jsx
  src/components/MessageCard/MessageCard.jsx
  src/pages/Edit.jsx
  src/pages/Post.jsx
  src/pages/Post.style.jsx
Labels: 페이지, 기능

#112 [#109] fix : header 이름 줄어들지 않는 버그 수정
  src/components/Header/PostHeader.style.jsx
Labels: bug

#115 [#114] fix : 로딩중 버튼 disabled
  src/components/Share/Popover.jsx
  src/pages/From.jsx
  src/pages/To.jsx
Labels: bug

#111 [#69] 로딩 화면 기능 추가
  src/assets/gifs/loading.gif
  src/assets/mock/mockReactions.js
  src/components/Modal/LoadingModal.jsx
  src/components/Modal/MessageCardModal.jsx
  src/components/Option/Option.jsx
  src/pages/From.jsx
  src/pages/PaperList.jsx
  src/pages/Post.jsx
  src/util/Loading.jsx
Labels: 기능

#118 [ #116] MessageCard 컴포넌트 불필요한 코드 제거
  src/components/MessageCard/MessageCard.jsx
Labels: bug

#120 [#119] netlify 배포를 위한 파일 추가
  public/_redirects
Labels: bug

#123 [#122] 404 페이지 추가
  src/App.jsx
  src/Error/ErrorFallback.jsx
  src/pages/NotFound.jsx
  src/styles/error/Error.style.jsx
Labels: 기능

#126 [#125] 무한 스크롤시 깜빡임이 있어 삭제
  src/components/Modal/LoadingModal.jsx
  src/pages/Post.jsx
Labels: bug

#138 [#137] fix : 유니코드 문자 정규표현식 변경
  src/styles/input/TextInput.jsx
Labels: bug

#140 [#139] 카드리스트 이모지 갭 수정 (모바일 버전)
  src/components/PaperCard/PaperCard.jsx
Labels: bug

#142 [#141] 이모지 클릭 쓰로틀링으로 수정
  package-lock.json
  package.json
  src/pages/Post.jsx
Labels: bug
